#
# e10.conf
#

Experiment:	10

BEAM:		param/BEAM/run04725_BcOutTracking.root
DCGEO:		param/DCGEO/DCGeomParam_e10_20231019
DSIZE:		param/DSIZE/DetSize_E10_0
HIST:		param/HIST/HistParam_E10_0
# FLDMAP:		fieldmap/StsFieldMap_20230731_BH14full_D1_2362A.dat
FLDMAP:         fieldmap/BH14full_20230711.dat
Q1SCALE:	0.65
Q2SCALE:	0.65
D1SCALE:	0.65

PK18:		1.2

Generator:	2

###### PhysicsList
EM:		0
DECAY: 		0
HADRON: 	0

TargetMaterial: Be
# TargetMaterial: C

CheckOverlap:	0

TREE:		0
