#
# e10_acc_9hesigma_kpi_QvarD0.86_Q0.89.conf
# D1SCALE fixed=0.86, Q1=Q2SCALE=0.89 (decoupled scan, set A)
#

Experiment:	10

DCGEO:		param/DCGEO/DCGeomParam_e10_9hesigma_kpi
DSIZE:		param/DSIZE/DetSize_E10_9hesigma_kpi
HIST:		param/HIST/HistParam_E10_9hesigma_kpi
FLDMAP:         fieldmap/BH14full_20230711.dat
Q1SCALE:	0.89
Q2SCALE:	0.89
D1SCALE:	0.86

Generator:	2
GenPID:		3
GenMomCent:	1.22
GenMomBite:	0.30
GenTheta:	20

EM:		0
DECAY: 		0
HADRON: 	0

TargetMaterial: Be
CheckOverlap:	0
TREE:		0
